// Generated by scripts/apply-evidence.js from the 1104-paper corpus evidence matrix. Do not edit.
export const EVIDENCE_SUMMARY = {"papers":1104,"relevant":602,"findings":1376,"maxSupport":29};
export const EVIDENCE_LEXICON = {
 "happy": {
  "adjust": [
   {
    "f": "gvi",
    "factor": 1.13,
    "support": 5.5,
    "against": 0,
    "conflict": false,
    "papers": [
     "W121869782",
     "W3212505812",
     "W2108098522",
     "W2915953456",
     "W2794423274",
     "W3217508649",
     "W4401525091",
     "W4412631107",
     "W4416808461"
    ]
   },
   {
    "f": "enclosureHW",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": [
     "W4391309507"
    ]
   },
   {
    "f": "svf",
    "factor": 0.962,
    "support": 1.5,
    "against": 0,
    "conflict": false,
    "papers": [
     "W4393250851",
     "W4416808461"
    ]
   },
   {
    "f": "utci",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": [
     "W3127373793"
    ]
   },
   {
    "f": "activeFrontage",
    "factor": 0.994,
    "support": 2,
    "against": 0,
    "conflict": false,
    "papers": [
     "W3007597810",
     "W99243737"
    ]
   },
   {
    "f": "seating",
    "factor": 0.994,
    "support": 2,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2979734888",
     "W99243737"
    ]
   },
   {
    "f": "isovistArea",
    "factor": 0.994,
    "support": 2,
    "against": 0,
    "conflict": false,
    "papers": [
     "S2:ae90b653446424dbe307ef0dc7a01bdaf2983832",
     "W3199121598",
     "W3212505812"
    ]
   },
   {
    "f": "roadDist",
    "factor": 1.045,
    "support": 3,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2428939645",
     "W3093985876",
     "W3127373793",
     "W3130322334",
     "W3157547930",
     "W4410144098"
    ]
   },
   {
    "f": "sunHours",
    "factor": 1,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "isovistPct",
    "factor": 1,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "shade",
    "factor": 1,
    "support": 0.5,
    "against": 0,
    "conflict": false,
    "papers": [
     "W99243737"
    ]
   }
  ],
  "added": [
   {
    "f": "waterView",
    "t": [
     0.1,
     0.5,
     1000000000,
     1000000000
    ],
    "w": 0.403,
    "src": [
     "corpus:7"
    ],
    "n": 7,
    "consistency": 1,
    "params": [
     "water_presence",
     "blue_space_view"
    ],
    "papers": [
     "W2002132641",
     "W2127136154",
     "W2147595461",
     "W4416808461",
     "W2794423274",
     "W2915953456",
     "W4214554745"
    ]
   }
  ]
 },
 "calm": {
  "adjust": [
   {
    "f": "gvi",
    "factor": 1.045,
    "support": 3,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2559768543",
     "W3023604562",
     "W3094276178"
    ]
   },
   {
    "f": "roadDist",
    "factor": 1.188,
    "support": 8,
    "against": 0,
    "conflict": false,
    "papers": [
     "W1605092369",
     "W4200341337",
     "W2100874253",
     "W2180030547",
     "W2244346191",
     "W2560670710",
     "W297688052",
     "W3039315801",
     "W3087980012",
     "W3093985876",
     "W4386418126"
    ]
   },
   {
    "f": "activeFrontage",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": [
     "W4391309507"
    ]
   },
   {
    "f": "wind",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "occlusions",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "waterView",
    "factor": 0.922,
    "support": 1,
    "against": 0,
    "conflict": false,
    "papers": [
     "W3083508329"
    ]
   },
   {
    "f": "skylineVar",
    "factor": 0.8,
    "support": 0,
    "against": 1,
    "conflict": false,
    "papers": [
     "W7147055493",
     "W7147325748"
    ]
   }
  ],
  "added": []
 },
 "lively": {
  "adjust": [
   {
    "f": "activeFrontage",
    "factor": 0.922,
    "support": 1,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2945765912",
     "W3204457184"
    ]
   },
   {
    "f": "seating",
    "factor": 1.045,
    "support": 3,
    "against": 0,
    "conflict": false,
    "papers": [
     "W4394923354",
     "W4405889866",
     "W4415680280"
    ]
   },
   {
    "f": "occlusions",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2945765912"
    ]
   },
   {
    "f": "isovistArea",
    "factor": 0.872,
    "support": 0.5,
    "against": 0,
    "conflict": false,
    "papers": [
     "W3199121598"
    ]
   },
   {
    "f": "enclosureHW",
    "factor": 0.872,
    "support": 0.5,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2054889709",
     "W2945765912"
    ]
   },
   {
    "f": "shade",
    "factor": 0.994,
    "support": 2,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2045241207",
     "W4394923354"
    ]
   },
   {
    "f": "edgeDist",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   }
  ],
  "added": [
   {
    "f": "gvi",
    "t": [
     0.06,
     0.3,
     1000000000,
     1000000000
    ],
    "w": 0.368,
    "src": [
     "corpus:4"
    ],
    "n": 4,
    "consistency": 1,
    "params": [
     "tree_canopy_cover",
     "vegetation_ndvi",
     "lawn_grass",
     "green_view_index"
    ],
    "papers": [
     "W2511574507",
     "W4380854093",
     "W4394923354",
     "W4415680280"
    ]
   }
  ]
 },
 "safe": {
  "adjust": [
   {
    "f": "openness",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "isovistArea",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "activeFrontage",
    "factor": 0.922,
    "support": 1,
    "against": 1,
    "conflict": false,
    "papers": [
     "W3085009681",
     "W3181114874"
    ]
   },
   {
    "f": "occlusions",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "jaggedness",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "gvi",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   }
  ],
  "added": []
 },
 "intimate": {
  "adjust": [
   {
    "f": "enclosureHW",
    "factor": 0.872,
    "support": 0.5,
    "against": 0,
    "conflict": false,
    "papers": [
     "W4316037750"
    ]
   },
   {
    "f": "isovistArea",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "roundness",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "edgeDist",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "svf",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   }
  ],
  "added": []
 },
 "spacious": {
  "adjust": [
   {
    "f": "isovistArea",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "svf",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "openness",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "enclosureHW",
    "factor": 0.922,
    "support": 1,
    "against": 0,
    "conflict": false,
    "papers": [
     "W4316037750"
    ]
   }
  ],
  "added": []
 },
 "restorative": {
  "adjust": [
   {
    "f": "gvi",
    "factor": 1.084,
    "support": 4,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2559768543",
     "W3023604562",
     "W3094276178",
     "W2915953456"
    ]
   },
   {
    "f": "waterView",
    "factor": 0.922,
    "support": 1,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2915953456",
     "W4312173606"
    ]
   },
   {
    "f": "roadDist",
    "factor": 0.994,
    "support": 2,
    "against": 0,
    "conflict": false,
    "papers": [
     "W1605092369",
     "W3087980012",
     "W3157547930"
    ]
   },
   {
    "f": "skylineVar",
    "factor": 0.962,
    "support": 1.5,
    "against": 0,
    "conflict": false,
    "papers": [
     "W7147055493",
     "W7147325748"
    ]
   },
   {
    "f": "utci",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   }
  ],
  "added": []
 },
 "mysterious": {
  "adjust": [
   {
    "f": "occlusions",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "jaggedness",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "openness",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "isovistArea",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   }
  ],
  "added": []
 },
 "comfortable": {
  "adjust": [
   {
    "f": "utci",
    "factor": 1.368,
    "support": 24,
    "against": 2,
    "conflict": false,
    "papers": [
     "W1846565783",
     "W1895160057",
     "W1949841688",
     "W1973785649",
     "W1980185467",
     "W2064437432",
     "W2300762800",
     "W2901112216",
     "W3033754149",
     "W3107669025",
     "W3128936126",
     "W4281746616"
    ]
   },
   {
    "f": "shade",
    "factor": 1.4,
    "support": 29,
    "against": 2,
    "conflict": false,
    "papers": [
     "W1498526867",
     "W1698816836",
     "W1735464075",
     "W2039196723",
     "W2045241207",
     "W2055973239",
     "W2300762800",
     "W2402931547",
     "W2627087201",
     "W2781965083",
     "W2796103100",
     "W2883689404"
    ]
   },
   {
    "f": "wind",
    "factor": 1.167,
    "support": 7,
    "against": 0,
    "conflict": false,
    "papers": [
     "W1980185467",
     "W1993031224",
     "W2027811510",
     "W2061170168",
     "W2083659651",
     "W2086571105",
     "W2136584032",
     "W2257317930",
     "W2258861694",
     "W2300762800",
     "W2749382328",
     "W2781965083"
    ]
   },
   {
    "f": "svf",
    "factor": 1.084,
    "support": 4,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2607241613",
     "W3023604562",
     "W3040419139",
     "W3216793944",
     "W4312214446",
     "W4321764521",
     "W4368405155",
     "W4396737074",
     "W4407742881",
     "W4412999250"
    ]
   }
  ],
  "added": [
   {
    "f": "gvi",
    "t": [
     0.06,
     0.3,
     1000000000,
     1000000000
    ],
    "w": 0.533,
    "src": [
     "corpus:46"
    ],
    "n": 46,
    "consistency": 0.89,
    "params": [
     "vegetation_ndvi",
     "tree_canopy_cover",
     "lawn_grass"
    ],
    "papers": [
     "W1735464075",
     "W1993031224",
     "W3153544187",
     "W4404373409",
     "W4417122602",
     "W1698816836",
     "W1839452767",
     "W1949841688",
     "W1968465470",
     "W1978443730",
     "W2060496785",
     "W2066358726"
    ]
   },
   {
    "f": "waterView",
    "t": [
     0.1,
     0.5,
     1000000000,
     1000000000
    ],
    "w": 0.393,
    "src": [
     "corpus:6"
    ],
    "n": 6,
    "consistency": 0.67,
    "params": [
     "water_presence"
    ],
    "papers": [
     "W1993031224",
     "W2086571105",
     "W2584823719",
     "W2889262240",
     "W3009412602",
     "W7212631283"
    ]
   },
   {
    "f": "enclosureHW",
    "t": [
     0.5,
     2.5,
     1000000000,
     1000000000
    ],
    "w": 0.489,
    "src": [
     "corpus:25"
    ],
    "n": 25,
    "consistency": 0.88,
    "params": [
     "enclosure_height_width",
     "street_width"
    ],
    "papers": [
     "W1645040285",
     "W1698816836",
     "W1735464075",
     "W1980185467",
     "W1996187877",
     "W2055973239",
     "W2901129702",
     "W2918274846",
     "W2977178115",
     "W2999700177",
     "W3085110501",
     "W3107669025"
    ]
   },
   {
    "f": "meanHeight",
    "t": [
     4,
     20,
     1000000000,
     1000000000
    ],
    "w": 0.433,
    "src": [
     "corpus:11"
    ],
    "n": 11,
    "consistency": 1,
    "params": [
     "building_height"
    ],
    "papers": [
     "W1498526867",
     "W2055973239",
     "W2065623771",
     "W2086571105",
     "W2101520475",
     "W2300762800",
     "W2781965083",
     "W2999700177",
     "W3006564631",
     "W4391265097",
     "W4392170493"
    ]
   },
   {
    "f": "sunHours",
    "t": [
     -1000000000,
     -1000000000,
     6,
     10.8
    ],
    "w": 0.382,
    "src": [
     "corpus:5"
    ],
    "n": 5,
    "consistency": -1,
    "params": [
     "sun_exposure_hours"
    ],
    "papers": [
     "W1498526867",
     "W1895160057",
     "W2257317930",
     "W3033754149",
     "W3128936126"
    ]
   }
  ]
 },
 "legible": {
  "adjust": [
   {
    "f": "roundness",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "occlusions",
    "factor": 0.6,
    "support": 0,
    "against": 2,
    "conflict": true,
    "papers": [
     "W3113960726",
     "W4401495048",
     "W4407690936"
    ]
   },
   {
    "f": "skylineVar",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "isovistArea",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "activeFrontage",
    "factor": 0.922,
    "support": 1,
    "against": 0,
    "conflict": false,
    "papers": [
     "W3007597810"
    ]
   }
  ],
  "added": [
   {
    "f": "waterView",
    "t": [
     0.1,
     0.5,
     1000000000,
     1000000000
    ],
    "w": 0.352,
    "src": [
     "corpus:3"
    ],
    "n": 3,
    "consistency": 1,
    "params": [
     "water_presence",
     "blue_space_view"
    ],
    "papers": [
     "W2127136154",
     "W4416808461",
     "W4214554745"
    ]
   }
  ]
 },
 "sociable": {
  "adjust": [
   {
    "f": "seating",
    "factor": 0.922,
    "support": 1,
    "against": 0,
    "conflict": false,
    "papers": [
     "W4405889866"
    ]
   },
   {
    "f": "edgeDist",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "shade",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "activeFrontage",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "isovistArea",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2992809306"
    ]
   },
   {
    "f": "wind",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   }
  ],
  "added": []
 },
 "active": {
  "adjust": [
   {
    "f": "isovistPct",
    "factor": 1,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "sunHours",
    "factor": 1,
    "support": 0.5,
    "against": 0,
    "conflict": false,
    "papers": [
     "W4212779166"
    ]
   },
   {
    "f": "shade",
    "factor": 1,
    "support": 0.5,
    "against": 0,
    "conflict": false,
    "papers": [
     "W2045241207"
    ]
   },
   {
    "f": "openness",
    "factor": 0.8,
    "support": 0,
    "against": 0,
    "conflict": false,
    "papers": []
   },
   {
    "f": "utci",
    "factor": 0.8,
    "support": 0,
    "against": 1,
    "conflict": false,
    "papers": [
     "W2131249234"
    ]
   }
  ],
  "added": [
   {
    "f": "gvi",
    "t": [
     0.06,
     0.3,
     1000000000,
     1000000000
    ],
    "w": 0.352,
    "src": [
     "corpus:3"
    ],
    "n": 3,
    "consistency": 1,
    "params": [
     "green_view_index",
     "tree_canopy_cover",
     "vegetation_ndvi",
     "lawn_grass"
    ],
    "papers": [
     "W3082422933",
     "W4380854093",
     "W3081061234"
    ]
   }
  ]
 }
};
